"""empty message

Revision ID: 26a39c34f2be
Revises: a52e0c30b50b
Create Date: 2018-05-20 21:14:36.670578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a39c34f2be'
down_revision = 'a52e0c30b50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s_user_info', sa.Column('password_hash', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s_user_info', 'password_hash')
    # ### end Alembic commands ###
