"""empty message

Revision ID: a52e0c30b50b
Revises: 
Create Date: 2018-05-20 21:09:30.207431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52e0c30b50b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s_group_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=30), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s_user_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('sign', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('s_chat_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('chat_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['s_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s_file',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=30), nullable=True),
    sa.Column('file_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['s_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s_group_user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['s_group_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['s_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s_image',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_name', sa.String(length=30), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['s_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s_user_group',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['s_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s_chat_user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['s_chat_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['s_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s_group_friend',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_group_id'], ['s_user_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['s_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s_group_friend')
    op.drop_table('s_chat_user')
    op.drop_table('s_user_group')
    op.drop_table('s_image')
    op.drop_table('s_group_user')
    op.drop_table('s_file')
    op.drop_table('s_chat_info')
    op.drop_table('s_user_info')
    op.drop_table('s_group_info')
    # ### end Alembic commands ###
